package com.ngbj.wallpaper.bean.greenBeanDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ngbj.wallpaper.bean.entityBean.HistoryBean;
import com.ngbj.wallpaper.bean.entityBean.WallpagerBean;

import com.ngbj.wallpaper.bean.greenBeanDao.HistoryBeanDao;
import com.ngbj.wallpaper.bean.greenBeanDao.WallpagerBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyBeanDaoConfig;
    private final DaoConfig wallpagerBeanDaoConfig;

    private final HistoryBeanDao historyBeanDao;
    private final WallpagerBeanDao wallpagerBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyBeanDaoConfig = daoConfigMap.get(HistoryBeanDao.class).clone();
        historyBeanDaoConfig.initIdentityScope(type);

        wallpagerBeanDaoConfig = daoConfigMap.get(WallpagerBeanDao.class).clone();
        wallpagerBeanDaoConfig.initIdentityScope(type);

        historyBeanDao = new HistoryBeanDao(historyBeanDaoConfig, this);
        wallpagerBeanDao = new WallpagerBeanDao(wallpagerBeanDaoConfig, this);

        registerDao(HistoryBean.class, historyBeanDao);
        registerDao(WallpagerBean.class, wallpagerBeanDao);
    }
    
    public void clear() {
        historyBeanDaoConfig.getIdentityScope().clear();
        wallpagerBeanDaoConfig.getIdentityScope().clear();
    }

    public HistoryBeanDao getHistoryBeanDao() {
        return historyBeanDao;
    }

    public WallpagerBeanDao getWallpagerBeanDao() {
        return wallpagerBeanDao;
    }

}
